/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.mbarak.showcase;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class UserProfile extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -5798189589406842232L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"UserProfile\",\"namespace\":\"io.mbarak.showcase\",\"fields\":[{\"name\":\"userId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"userValue1\",\"type\":\"double\"},{\"name\":\"userValue2\",\"type\":\"long\"},{\"name\":\"userValue3\",\"type\":\"double\"},{\"name\":\"userValue4\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"timestamp\",\"type\":\"long\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<UserProfile> ENCODER =
      new BinaryMessageEncoder<UserProfile>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<UserProfile> DECODER =
      new BinaryMessageDecoder<UserProfile>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<UserProfile> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<UserProfile> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<UserProfile>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this UserProfile to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a UserProfile from a ByteBuffer. */
  public static UserProfile fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.String userId;
  @Deprecated public double userValue1;
  @Deprecated public long userValue2;
  @Deprecated public double userValue3;
  @Deprecated public java.lang.String userValue4;
  @Deprecated public long timestamp;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public UserProfile() {}

  /**
   * All-args constructor.
   * @param userId The new value for userId
   * @param userValue1 The new value for userValue1
   * @param userValue2 The new value for userValue2
   * @param userValue3 The new value for userValue3
   * @param userValue4 The new value for userValue4
   * @param timestamp The new value for timestamp
   */
  public UserProfile(java.lang.String userId, java.lang.Double userValue1, java.lang.Long userValue2, java.lang.Double userValue3, java.lang.String userValue4, java.lang.Long timestamp) {
    this.userId = userId;
    this.userValue1 = userValue1;
    this.userValue2 = userValue2;
    this.userValue3 = userValue3;
    this.userValue4 = userValue4;
    this.timestamp = timestamp;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return userId;
    case 1: return userValue1;
    case 2: return userValue2;
    case 3: return userValue3;
    case 4: return userValue4;
    case 5: return timestamp;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: userId = (java.lang.String)value$; break;
    case 1: userValue1 = (java.lang.Double)value$; break;
    case 2: userValue2 = (java.lang.Long)value$; break;
    case 3: userValue3 = (java.lang.Double)value$; break;
    case 4: userValue4 = (java.lang.String)value$; break;
    case 5: timestamp = (java.lang.Long)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'userId' field.
   * @return The value of the 'userId' field.
   */
  public java.lang.String getUserId() {
    return userId;
  }

  /**
   * Sets the value of the 'userId' field.
   * @param value the value to set.
   */
  public void setUserId(java.lang.String value) {
    this.userId = value;
  }

  /**
   * Gets the value of the 'userValue1' field.
   * @return The value of the 'userValue1' field.
   */
  public java.lang.Double getUserValue1() {
    return userValue1;
  }

  /**
   * Sets the value of the 'userValue1' field.
   * @param value the value to set.
   */
  public void setUserValue1(java.lang.Double value) {
    this.userValue1 = value;
  }

  /**
   * Gets the value of the 'userValue2' field.
   * @return The value of the 'userValue2' field.
   */
  public java.lang.Long getUserValue2() {
    return userValue2;
  }

  /**
   * Sets the value of the 'userValue2' field.
   * @param value the value to set.
   */
  public void setUserValue2(java.lang.Long value) {
    this.userValue2 = value;
  }

  /**
   * Gets the value of the 'userValue3' field.
   * @return The value of the 'userValue3' field.
   */
  public java.lang.Double getUserValue3() {
    return userValue3;
  }

  /**
   * Sets the value of the 'userValue3' field.
   * @param value the value to set.
   */
  public void setUserValue3(java.lang.Double value) {
    this.userValue3 = value;
  }

  /**
   * Gets the value of the 'userValue4' field.
   * @return The value of the 'userValue4' field.
   */
  public java.lang.String getUserValue4() {
    return userValue4;
  }

  /**
   * Sets the value of the 'userValue4' field.
   * @param value the value to set.
   */
  public void setUserValue4(java.lang.String value) {
    this.userValue4 = value;
  }

  /**
   * Gets the value of the 'timestamp' field.
   * @return The value of the 'timestamp' field.
   */
  public java.lang.Long getTimestamp() {
    return timestamp;
  }

  /**
   * Sets the value of the 'timestamp' field.
   * @param value the value to set.
   */
  public void setTimestamp(java.lang.Long value) {
    this.timestamp = value;
  }

  /**
   * Creates a new UserProfile RecordBuilder.
   * @return A new UserProfile RecordBuilder
   */
  public static io.mbarak.showcase.UserProfile.Builder newBuilder() {
    return new io.mbarak.showcase.UserProfile.Builder();
  }

  /**
   * Creates a new UserProfile RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new UserProfile RecordBuilder
   */
  public static io.mbarak.showcase.UserProfile.Builder newBuilder(io.mbarak.showcase.UserProfile.Builder other) {
    return new io.mbarak.showcase.UserProfile.Builder(other);
  }

  /**
   * Creates a new UserProfile RecordBuilder by copying an existing UserProfile instance.
   * @param other The existing instance to copy.
   * @return A new UserProfile RecordBuilder
   */
  public static io.mbarak.showcase.UserProfile.Builder newBuilder(io.mbarak.showcase.UserProfile other) {
    return new io.mbarak.showcase.UserProfile.Builder(other);
  }

  /**
   * RecordBuilder for UserProfile instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<UserProfile>
    implements org.apache.avro.data.RecordBuilder<UserProfile> {

    private java.lang.String userId;
    private double userValue1;
    private long userValue2;
    private double userValue3;
    private java.lang.String userValue4;
    private long timestamp;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(io.mbarak.showcase.UserProfile.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.userId)) {
        this.userId = data().deepCopy(fields()[0].schema(), other.userId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.userValue1)) {
        this.userValue1 = data().deepCopy(fields()[1].schema(), other.userValue1);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.userValue2)) {
        this.userValue2 = data().deepCopy(fields()[2].schema(), other.userValue2);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.userValue3)) {
        this.userValue3 = data().deepCopy(fields()[3].schema(), other.userValue3);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.userValue4)) {
        this.userValue4 = data().deepCopy(fields()[4].schema(), other.userValue4);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[5].schema(), other.timestamp);
        fieldSetFlags()[5] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing UserProfile instance
     * @param other The existing instance to copy.
     */
    private Builder(io.mbarak.showcase.UserProfile other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.userId)) {
        this.userId = data().deepCopy(fields()[0].schema(), other.userId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.userValue1)) {
        this.userValue1 = data().deepCopy(fields()[1].schema(), other.userValue1);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.userValue2)) {
        this.userValue2 = data().deepCopy(fields()[2].schema(), other.userValue2);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.userValue3)) {
        this.userValue3 = data().deepCopy(fields()[3].schema(), other.userValue3);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.userValue4)) {
        this.userValue4 = data().deepCopy(fields()[4].schema(), other.userValue4);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[5].schema(), other.timestamp);
        fieldSetFlags()[5] = true;
      }
    }

    /**
      * Gets the value of the 'userId' field.
      * @return The value.
      */
    public java.lang.String getUserId() {
      return userId;
    }

    /**
      * Sets the value of the 'userId' field.
      * @param value The value of 'userId'.
      * @return This builder.
      */
    public io.mbarak.showcase.UserProfile.Builder setUserId(java.lang.String value) {
      validate(fields()[0], value);
      this.userId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'userId' field has been set.
      * @return True if the 'userId' field has been set, false otherwise.
      */
    public boolean hasUserId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'userId' field.
      * @return This builder.
      */
    public io.mbarak.showcase.UserProfile.Builder clearUserId() {
      userId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'userValue1' field.
      * @return The value.
      */
    public java.lang.Double getUserValue1() {
      return userValue1;
    }

    /**
      * Sets the value of the 'userValue1' field.
      * @param value The value of 'userValue1'.
      * @return This builder.
      */
    public io.mbarak.showcase.UserProfile.Builder setUserValue1(double value) {
      validate(fields()[1], value);
      this.userValue1 = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'userValue1' field has been set.
      * @return True if the 'userValue1' field has been set, false otherwise.
      */
    public boolean hasUserValue1() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'userValue1' field.
      * @return This builder.
      */
    public io.mbarak.showcase.UserProfile.Builder clearUserValue1() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'userValue2' field.
      * @return The value.
      */
    public java.lang.Long getUserValue2() {
      return userValue2;
    }

    /**
      * Sets the value of the 'userValue2' field.
      * @param value The value of 'userValue2'.
      * @return This builder.
      */
    public io.mbarak.showcase.UserProfile.Builder setUserValue2(long value) {
      validate(fields()[2], value);
      this.userValue2 = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'userValue2' field has been set.
      * @return True if the 'userValue2' field has been set, false otherwise.
      */
    public boolean hasUserValue2() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'userValue2' field.
      * @return This builder.
      */
    public io.mbarak.showcase.UserProfile.Builder clearUserValue2() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'userValue3' field.
      * @return The value.
      */
    public java.lang.Double getUserValue3() {
      return userValue3;
    }

    /**
      * Sets the value of the 'userValue3' field.
      * @param value The value of 'userValue3'.
      * @return This builder.
      */
    public io.mbarak.showcase.UserProfile.Builder setUserValue3(double value) {
      validate(fields()[3], value);
      this.userValue3 = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'userValue3' field has been set.
      * @return True if the 'userValue3' field has been set, false otherwise.
      */
    public boolean hasUserValue3() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'userValue3' field.
      * @return This builder.
      */
    public io.mbarak.showcase.UserProfile.Builder clearUserValue3() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'userValue4' field.
      * @return The value.
      */
    public java.lang.String getUserValue4() {
      return userValue4;
    }

    /**
      * Sets the value of the 'userValue4' field.
      * @param value The value of 'userValue4'.
      * @return This builder.
      */
    public io.mbarak.showcase.UserProfile.Builder setUserValue4(java.lang.String value) {
      validate(fields()[4], value);
      this.userValue4 = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'userValue4' field has been set.
      * @return True if the 'userValue4' field has been set, false otherwise.
      */
    public boolean hasUserValue4() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'userValue4' field.
      * @return This builder.
      */
    public io.mbarak.showcase.UserProfile.Builder clearUserValue4() {
      userValue4 = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'timestamp' field.
      * @return The value.
      */
    public java.lang.Long getTimestamp() {
      return timestamp;
    }

    /**
      * Sets the value of the 'timestamp' field.
      * @param value The value of 'timestamp'.
      * @return This builder.
      */
    public io.mbarak.showcase.UserProfile.Builder setTimestamp(long value) {
      validate(fields()[5], value);
      this.timestamp = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'timestamp' field has been set.
      * @return True if the 'timestamp' field has been set, false otherwise.
      */
    public boolean hasTimestamp() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'timestamp' field.
      * @return This builder.
      */
    public io.mbarak.showcase.UserProfile.Builder clearTimestamp() {
      fieldSetFlags()[5] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public UserProfile build() {
      try {
        UserProfile record = new UserProfile();
        record.userId = fieldSetFlags()[0] ? this.userId : (java.lang.String) defaultValue(fields()[0]);
        record.userValue1 = fieldSetFlags()[1] ? this.userValue1 : (java.lang.Double) defaultValue(fields()[1]);
        record.userValue2 = fieldSetFlags()[2] ? this.userValue2 : (java.lang.Long) defaultValue(fields()[2]);
        record.userValue3 = fieldSetFlags()[3] ? this.userValue3 : (java.lang.Double) defaultValue(fields()[3]);
        record.userValue4 = fieldSetFlags()[4] ? this.userValue4 : (java.lang.String) defaultValue(fields()[4]);
        record.timestamp = fieldSetFlags()[5] ? this.timestamp : (java.lang.Long) defaultValue(fields()[5]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<UserProfile>
    WRITER$ = (org.apache.avro.io.DatumWriter<UserProfile>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<UserProfile>
    READER$ = (org.apache.avro.io.DatumReader<UserProfile>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
